library(tidyverse)
library(knitr)
library(data.table)
library(quanteda)
library(methods)
library(utils)
library(LaF)
library(caret)
library(profvis)
library(seplyr)


set.seed(12349)

source("next_word.R")
source("good_turing.R")
source("model_prep.R")
source("load_data.R")
source("create_toks.R")
source("convert_to_data_frame.R")
source("score_model.R")
source("full_test.R")

load_data()

test_toks <- create_toks(test, .0005)
test_df <- convert_to_data_frame(test_toks)
rm(test)

full_test(train, test_df, p = .1, min_words = 1, stem = F)
full_test(train, test_df, p = .1, min_words = 1, stem = T)
full_test(train, test_df, p = .1, min_words = 2, stem = F)
full_test(train, test_df, p = .1, min_words = 2, stem = T)
full_test(train, test_df, p = .1, min_words = 3, stem = F)
full_test(train, test_df, p = .1, min_words = 3, stem = T)
full_test(train, test_df, p = .3, min_words = 3, stem = F)
full_test(train, test_df, p = .5, min_words = 3, stem = F)
