---
title: "Quiz_1"
author: "Kevin Goldsmith"
date: "2/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, message = FALSE, echo = FALSE}
source("coverage.R")
library(readr)
library(data.table)
library(tm)
library(quanteda)
library(readtext)
library(methods)
library(utils)
library(LaF)
library(ggplot2)
source("create_file.R")
source("next_word.R")

set.seed(12345)

myURL <- "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"

dateDownloaded <- date()

if(!file.exists("rawdata.zip")){
  download.file(myURL, destfile = "rawdata.zip", method = "curl")
  unzip("rawdata.zip")
}


#Create combined corpus
create_file(US.blogs_corp, "~/CapstoneProject/final/en_US/en_US.blogs.txt", 100)
create_file(US.twit_corp, "~/CapstoneProject/final/en_US/en_US.twitter.txt", 100)
create_file(US.news_corp, "~/CapstoneProject/final/en_US/en_US.news.txt", 100)

US.blogs_corp <- corpus(US.blogs_corp)
US.news_corp <- corpus(US.news_corp)
US.twit_corp <- corpus(US.twit_corp)
combined_corp <- US.blogs_corp + US.news_corp + US.twit_corp
rm(US.blogs_corp, US.news_corp, US.twit_corp)


#download external dictionaries 
download.file("https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en", 
              destfile = "profanity.txt", method = "curl")

profanity <- readLines("profanity.txt")

download.file("https://raw.githubusercontent.com/dwyl/english-words/master/words.txt", 
              destfile = "english.txt", method = "curl")

all_english <- readLines("english.txt")

#data cleanup and manipulation 
combined_tok <- tokens(combined_corp)
combined_tok <- tokens(combined_tok, remove_punct = TRUE, remove_numbers = TRUE)
combined_tok <- tokens_select(combined_tok, pattern = profanity, selection = "remove")
combined_tok <- tokens_select(combined_tok, pattern = all_english, selection = "keep")
combined_dfm <- dfm(combined_tok)
combined_ngrams <- tokens_ngrams(combined_tok, 2:3)
rm(profanity)
rm(all_english)
```

```{r quiz 1 functions, echo = FALSE}
max(sapply(US.blogs_corp,nchar))
max(sapply(US.news_corp,nchar))
max(sapply(US.twit_corp,nchar))

textstat_frequency(dfm_select(dfm(US.twit_corp), pattern = "love", case_insensitive =  FALSE))$docfreq/
  textstat_frequency(dfm_select(dfm(US.twit_corp), pattern = "hate", case_insensitive = FALSE))$docfreq

textstat_frequency(dfm_select(dfm(US.twit_corp), pattern = "biostats"))

textstat_frequency(dfm_select(dfm(US.twit_corp), pattern = 
                                "A computer once beat me at chess, but it was no match for me at kickboxing")
                   )

```